# -*- coding: utf-8 -*-
"""Yashika Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwL_0KtSWJnwQFY2DCKxeGyK2fxR6BEQ
"""

# Yashika Singh Portfolio - Streamlit App

import streamlit as st
from PIL import Image
import base64

# ---------- CONFIG ---------- #
st.set_page_config(page_title="Yashika Singh | Portfolio", page_icon="🧠", layout="wide")

# ---------- HELPER ---------- #
def load_resume(file_path):
    with open(file_path, "rb") as f:
        return f.read()

def pdf_download_button(file_path, label):
    with open(file_path, "rb") as f:
        base64_pdf = base64.b64encode(f.read()).decode('utf-8')
        pdf_display = f"""
        <a href="data:application/pdf;base64,{base64_pdf}" download="Yashika_Singh_Resume.pdf">
            <button style='padding:0.5rem 1rem; font-size:1rem; border:none; background:#4CAF50; color:white; border-radius:5px;'>{label}</button>
        </a>"""
        st.markdown(pdf_display, unsafe_allow_html=True)

# ---------- SIDEBAR NAV ---------- #
pages = ["Home", "About Me", "Projects", "Research", "Contact"]
st.sidebar.title("Navigation")
selection = st.sidebar.radio("Go to", pages)

# ---------- AVATAR ---------- #
avatar = Image.open("avatar.jpg")  # Add your avatar image in the root folder

# ---------- HOME ---------- #
if selection == "Home":
    col1, col2 = st.columns([1, 3])
    with col1:
        st.image(avatar, width=150)
    with col2:
        st.title("Yashika Singh")
        st.write("AI/ML Engineer | MOVE Fellow @ Handshake | Former Data Scientist and Data Analyst @ Axtria | Open to Full-Time AI/ML Roles (OPT)")
        st.write("Building end-to-end intelligent systems powered by AI and ML")
        pdf_download_button("Yashika_Singh_Resume.pdf", "Download Resume")

# ---------- ABOUT ME ---------- #
elif selection == "About Me":
    st.header("👩‍💼 About Me")
    st.markdown("""
    AI/ML Engineer with around 4 years of experience building end-to-end AI products, from LLM-powered applications to ML
models. Skilled in RAG, prompt engineering, and multimodal AI, with production experience delivering projects at Product
Manager Accelerator under Dr. Nancy Li, as Lead AI Engineer at Columbia University’s Summer Startup Program and as AI/ML
Technical Lead for a stealth fashion startup in New York, owning the end-to-end AI architecture and roadmap. Selected for the
prestigious MOVE Program by Handshake, recognizing top Master’s students for leadership and innovation in technology.
    """)

    with st.expander("📚 Education"):
        st.markdown("""
- **MS in Artificial Intelligence**, Yeshiva University, New York (2025)  
- **BTech in Computer Science**, Galgotias College of Engineering and Technology, India (2021)
        """)

    with st.expander("💻 Programming Languages"):
        st.markdown("""
Python, C, C++, JavaScript, SQL
        """)

    with st.expander("🧠 Skills"):
        st.markdown("""
Data Analysis, Machine Learning, Deep Learning, Natural Language Processing (NLP), Convolutional Neural
Networks (CNN), Automatic Speech Recognition (ASR), Advanced Analytics, Predictive Modeling, Statistics, Mathe-
matics, Exploratory Data Analysis (EDA), Whisper, Large Language Models (LLM), Prompt Engineering, Generative
AI, Retrieval-Augmented Generation (RAG), MLOps, CI/CD Pipelines, MySQL, PostgreSQL, Extract-Transform-Load
(ETL), HTML5, CSS, Technical Writing and Documentation
        """)

    with st.expander("🛠️ Developer Tools & Cloud"):
        st.markdown("""
VS Code, Amazon Apache Airflow (DAGs), Azure Data Factory, AWS, Google Cloud Plat-
form (GCP), Git, TensorFlow, Streamlit, Tableau, Microsoft Excel, PowerBI, PyTorch, Computer Vision, Anaconda,
Jupyter, Google Colab, Pandas, Scikit-learn, Matplotlib, Data Pipelines, Databricks
        """)


# ---------- PROJECTS ---------- #
elif selection == "Projects":
    st.header("🧠 Projects")
    st.subheader(" Drowsiness Detection for Drivers")
    st.write("Built a CNN-based, real-time system using TensorFlow to detect driver fatigue and improve road safety with validation accuracy around 95%.")
    st.markdown("[📄 Read Paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=KctNEjgAAAAJ&citation_for_view=KctNEjgAAAAJ:d1gkVwhDpl0C)")

    st.subheader(" Detection of Cardiomegaly in Dogs")
    st.write("Created a deep learning model using custom CNN for X-ray analysis and automating veterinary diagnostics with an accuracy of 76.75%, surpassing the benchmark set by VGG16 (75%).")
    st.markdown("[📄 Read Paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=KctNEjgAAAAJ&citation_for_view=KctNEjgAAAAJ:u-x6o8ySG0sC)")

# ---------- RESEARCH ---------- #
elif selection == "Research":
    st.header("📚 Research & Patent")
    st.markdown("**Google Scholar:** [Visit Profile](https://scholar.google.com/citations?user=KctNEjgAAAAJ&hl=en)")
    
# ---------- CONTACT ---------- #
elif selection == "Contact":
    st.header("📬 Contact")
    st.write("📧 yashika6499@gmail.com")
    st.write("🔗 [LinkedIn](https://www.linkedin.com/in/yashika-singh-944700195/)")
    st.write("💻 [GitHub](https://github.com/yashikasingh6499)")

# ---------- FOOTER ---------- #
st.markdown("---")
st.markdown("Made with using Streamlit | © 2025 Yashika Singh")

