# -*- coding: utf-8 -*-
"""Yashika Portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwL_0KtSWJnwQFY2DCKxeGyK2fxR6BEQ
"""

# Yashika Singh Portfolio - Streamlit App

import streamlit as st
from PIL import Image
import base64

# ---------- CONFIG ---------- #
st.set_page_config(page_title="Yashika Singh | Portfolio", page_icon="🧠", layout="wide")

# ---------- HELPER ---------- #
def load_resume(file_path):
    with open(file_path, "rb") as f:
        return f.read()

def pdf_download_button(file_path, label):
    with open(file_path, "rb") as f:
        base64_pdf = base64.b64encode(f.read()).decode('utf-8')
        pdf_display = f"""
        <a href="data:application/pdf;base64,{base64_pdf}" download="Yashika_Singh_Resume.pdf">
            <button style='padding:0.5rem 1rem; font-size:1rem; border:none; background:#4CAF50; color:white; border-radius:5px;'>{label}</button>
        </a>"""
        st.markdown(pdf_display, unsafe_allow_html=True)

# ---------- SIDEBAR NAV ---------- #
pages = ["Home", "About Me", "Projects", "Research", "Contact"]
st.sidebar.title("Navigation")
selection = st.sidebar.radio("Go to", pages)

# ---------- AVATAR ---------- #
avatar = Image.open("avatar.jpg")  # Add your avatar image in the root folder

# ---------- HOME ---------- #
if selection == "Home":
    col1, col2 = st.columns([1, 3])
    with col1:
        st.image(avatar, width=150)
    with col2:
        st.title("Yashika Singh")
        st.write("AI/ML Engineer Intern | Master’s in Artificial Intelligence, New York | Open to Full-Time AI/ML Roles")
        st.write("Building end-to-end intelligent systems powered by AI and ML")
        pdf_download_button("Yashika_Singh_Resume.pdf", "Download Resume")

# ---------- ABOUT ME ---------- #
elif selection == "About Me":
    st.header("👩‍💼 About Me")
    st.write("""
    Innovative and driven AI/ML Engineer with 3+ years of hands-on experience building end-to-end solutions in Machine Learning, Generative AI, NLP, and Data Engineering. Adept at designing real-world applications—from AI-driven interview platforms to healthcare diagnostics—powered by deep learning, LLMs, and scalable data pipelines. Holds a filed patent for a novel authentication system, reflecting a strong foundation in problem-solving and originality. Passionate about pushing the boundaries of AI to craft impactful, human-centric solutions that drive automation, enhance decision-making, and bridge the gap between research and real-world use.

    **Education:**
    - MS in Artificial Intelligence, Yeshiva University, New York (2025)
    - BTech in Computer Science, Galgotias College of Engineering and Technology, India (2021)

    **Programming Languages:** Python, C, C++, JavaScript, SQL

    **Skills:** Data Analysis, Machine Learning, Deep Learning, Natural Language Processing (NLP), Convolutional Neural Networks (CNN), Automatic Speech Recognition (ASR), Advanced Analytics, Predictive Modeling, Statistics, Mathematics, Exploratory Data Analysis (EDA), Whisper, Large Language Models (LLM), Prompt Engineering, Generative AI, Retrieval-Augmented Generation (RAG), MLOps, CI/CD Pipelines, MySQL, PostgreSQL, Extract-Transform-Load (ETL), HTML5, CSS, Technical Writing and Documentation

    **Developer Tools/Cloud:** VS Code, Amazon Apache Airflow (DAGs), Azure Data Factory, AWS, Google Cloud Plat-
form (GCP), Git, TensorFlow, Streamlit, Tableau, Microsoft Excel, PowerBI, PyTorch, Computer Vision, Anaconda,
Jupyter, Google Colab, Pandas, Scikit-learn, Matplotlib, Data Pipelines, Databricks

    """)

# ---------- PROJECTS ---------- #
elif selection == "Projects":
    st.header("🧠 Projects")
    st.subheader("1. Automatic Teaching via Vision-Language RAG")
    st.write("Develop a Vision-Language RAG model integrating advanced AI, visual data, and textual information, leveraging open-source models like Whisper and Llama 3.2 11B Vision-Instruct Model to enhance interactive learning and enrich the educational experience.")

    st.subheader("2. Drowsiness Detection for Drivers")
    st.write("Built a CNN-based, real-time system using TensorFlow to detect driver fatigue and improve road safety with validation accuracy around 95%.")
    st.markdown("[📄 Read Paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=KctNEjgAAAAJ&citation_for_view=KctNEjgAAAAJ:d1gkVwhDpl0C)")

    st.subheader("3. Detection of Cardiomegaly in Dogs")
    st.write("Created a deep learning model using custom CNN for X-ray analysis and automating veterinary diagnostics with an accuracy of 76.75%, surpassing the benchmark set by VGG16 (75%).")
    st.markdown("[📄 Read Paper](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=KctNEjgAAAAJ&citation_for_view=KctNEjgAAAAJ:u-x6o8ySG0sC)")

# ---------- RESEARCH ---------- #
elif selection == "Research":
    st.header("📚 Research & Patent")
    st.markdown("**Google Scholar:** [Visit Profile](https://scholar.google.com/citations?user=KctNEjgAAAAJ&hl=en)")
    st.markdown("**Patent:** PEHCHAAN - An Authentication System to reduce fake social accounts (Filed: Nov 2020)")

# ---------- CONTACT ---------- #
elif selection == "Contact":
    st.header("📬 Contact")
    st.write("📧 yashika6499@gmail.com")
    st.write("🔗 [LinkedIn](https://www.linkedin.com/in/yashika-singh-944700195/)")
    st.write("💻 [GitHub](https://github.com/yashikasingh6499)")

# ---------- FOOTER ---------- #
st.markdown("---")
st.markdown("Made with using Streamlit | © 2025 Yashika Singh")

